"""empty message

Revision ID: 364112df7caf
Revises: 
Create Date: 2019-07-22 23:10:09.884749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '364112df7caf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('cat_name', sa.String(length=50), nullable=True))
    op.drop_column('category', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('name', mysql.VARCHAR(collation=u'utf8_bin', length=50), nullable=True))
    op.drop_column('category', 'cat_name')
    # ### end Alembic commands ###
