"""empty message

Revision ID: 3c774ef607d3
Revises: d28359c0ba2e
Create Date: 2019-06-06 10:20:38.112119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c774ef607d3'
down_revision = 'd28359c0ba2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('code', sa.String(length=20), nullable=True))
    op.add_column('inventory', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('inventory', sa.Column('description', sa.String(length=150), nullable=True))
    op.add_column('inventory', sa.Column('file', sa.String(length=150), nullable=True))
    op.add_column('inventory', sa.Column('location', sa.String(length=50), nullable=True))
    op.add_column('inventory', sa.Column('material', sa.String(length=50), nullable=True))
    op.add_column('inventory', sa.Column('perbox', sa.Integer(), nullable=True))
    op.add_column('inventory', sa.Column('updated_date', sa.DateTime(), nullable=True))
    op.add_column('loctite', sa.Column('batch', sa.Integer(), nullable=True))
    op.add_column('loctite', sa.Column('code', sa.String(length=20), nullable=True))
    op.add_column('loctite', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('loctite', sa.Column('description', sa.String(length=150), nullable=True))
    op.add_column('loctite', sa.Column('expiry_date', sa.DateTime(), nullable=True))
    op.add_column('loctite', sa.Column('file', sa.String(length=150), nullable=True))
    op.add_column('loctite', sa.Column('updated_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loctite', 'updated_date')
    op.drop_column('loctite', 'file')
    op.drop_column('loctite', 'expiry_date')
    op.drop_column('loctite', 'description')
    op.drop_column('loctite', 'created_date')
    op.drop_column('loctite', 'code')
    op.drop_column('loctite', 'batch')
    op.drop_column('inventory', 'updated_date')
    op.drop_column('inventory', 'perbox')
    op.drop_column('inventory', 'material')
    op.drop_column('inventory', 'location')
    op.drop_column('inventory', 'file')
    op.drop_column('inventory', 'description')
    op.drop_column('inventory', 'created_date')
    op.drop_column('inventory', 'code')
    # ### end Alembic commands ###
