"""empty message

Revision ID: 54e4566abc4d
Revises: 
Create Date: 2019-07-20 15:17:06.399048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54e4566abc4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('cid')
    )
    op.add_column(u'inventory', sa.Column('cid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inventory', 'category', ['cid'], ['cid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_column(u'inventory', 'cid')
    op.drop_table('category')
    # ### end Alembic commands ###
