"""empty message

Revision ID: 62515a27186a
Revises: 
Create Date: 2019-07-26 17:58:04.430827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62515a27186a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('cat_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('cid')
    )
    op.add_column(u'inventory', sa.Column('cid', sa.Integer(), nullable=True))
    op.add_column(u'inventory', sa.Column('rack', sa.String(length=50), nullable=True))
    op.add_column(u'inventory', sa.Column('unit_code', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'inventory', 'category', ['cid'], ['cid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_column(u'inventory', 'unit_code')
    op.drop_column(u'inventory', 'rack')
    op.drop_column(u'inventory', 'cid')
    op.drop_table('category')
    # ### end Alembic commands ###
