"""empty message

Revision ID: c278452a3b7b
Revises: 
Create Date: 2019-07-23 14:00:30.508537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c278452a3b7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('rack', sa.String(length=50), nullable=True))
    op.add_column('inventory', sa.Column('unit_code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'unit_code')
    op.drop_column('inventory', 'rack')
    # ### end Alembic commands ###
