"""empty message

Revision ID: f15404647aa6
Revises: 8b2234ca52c5
Create Date: 2019-07-01 20:14:17.364838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f15404647aa6'
down_revision = '8b2234ca52c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse',
    sa.Column('wid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('wid')
    )
    op.add_column(u'inventory', sa.Column('wid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inventory', 'warehouse', ['wid'], ['wid'])
    op.add_column(u'loctite', sa.Column('wid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'loctite', 'warehouse', ['wid'], ['wid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loctite', type_='foreignkey')
    op.drop_column(u'loctite', 'wid')
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_column(u'inventory', 'wid')
    op.drop_table('warehouse')
    # ### end Alembic commands ###
