// Inventory Actions

// Get
export const INVENTORY_API_FAILURE = "INVENTORY_API_FAILURE";
export const GET_ALL_INVENTORY = "GET_ALL_INVENTORY";
export const GET_ALL_INVENTORY_SUCCESS = "GET_ALL_INVENTORY_SUCCESS";

// view inventory
export const GET_INVENTORY = "GET_INVENTORY";
export const GET_INVENTORY_SUCCESS = "GET_INVENTORY_SUCCESS";
export const ON_CHANGE_INVENTORY_LIST = "ON_CHANGE_INVENTORY_LIST";
// new inventory
export const SUBMIT_INVENTORY_FORM = "SUBMIT_INVENTORY_FORM";
export const SUBMIT_INVENTORY_SUCCESS = "SUBMIT_INVENTORY_SUCCESS";
export const SUBMIT_INVENTORY_FAILURE = "SUBMIT_INVENTORY_FAILURE";
export const CLEAR_INVENTORY_FORM = "CLEAR_INVENTORY_FORM";
export const HANDLE_INV_FORM_CHANGE = "HANDLE_INV_FORM_CHANGE";
// edit
export const START_EDIT_INVENTORY = "START_EDIT_INVENTORY";
export const START_EDIT_INVENTORY_SUCCESS = "START_EDIT_INVENTORY_SUCCESS";
export const START_EDIT_INVENTORY_FAILURE = "START_EDIT_INVENTORY_FAILURE";

export const EDIT_INVENTORY = "EDIT_INVENTORY";
export const EDIT_INVENTORY_SUCCESS = "EDIT_INVENTORY_SUCCESS";
export const EDIT_INVENTORY_FAILURE = "EDIT_INVENTORY_FAILURE";

// Delete
export const DELETE_INVENTORY = "DELETE_INVENTORY";
export const DELETE_INVENTORY_SUCCESS = "DELETE_INVENTORY_SUCCESS";
export const DELETE_INVENTORY_FAILURE = "DELETE_INVENTORY_FAILURE";
