// Inventory Actions
export const INVENTORY_API_FAILURE = "INVENTORY_API_FAILURE";
export const GET_ALL_INVENTORY = "GET_ALL_INVENTORY";
export const GET_ALL_INVENTORY_SUCCESS = "GET_ALL_INVENTORY_SUCCESS";

export const ON_CHANGE_INVENTORY_LIST = "ON_CHANGE_INVENTORY_LIST";

// view inventory
export const GET_INVENTORY = "GET_INVENTORY";
export const GET_INVENTORY_SUCCESS = "GET_INVENTORY_SUCCESS";
// new inventory
export const SUBMIT_INVENTORY_FORM = "SUBMIT_INVENTORY_FORM";
export const SUBMIT_INVENTORY_SUCCESS = "SUBMIT_INVENTORY_SUCCESS";
export const SUBMIT_INVENTORY_FAILURE = "SUBMIT_INVENTORY_FAILURE";
export const CLEAR_INVENTORY_FORM = "CLEAR_INVENTORY_FORM";
// edit
export const START_EDIT_INVENTORY = "START_EDIT_INVENTORY";
export const START_EDIT_INVENTORY_SUCCESS = "START_EDIT_INVENTORY_SUCCESS";
export const START_EDIT_INVENTORY_FAILURE = "START_EDIT_INVENTORY_FAILURE";
