// Loctite Actions

// get
export const LOCTITE_API_FAILURE = "LOCTITE_API_FAILURE";
export const GET_ALL_LOCTITE = "GET_ALL_LOCTITE";
export const GET_ALL_LOCTITE_SUCCESS = "GET_ALL_LOCTITE_SUCCESS";
// view loctite
export const VIEW_LOCTITE = "VIEW_LOCTITE";
export const VIEW_LOCTITE_SUCCESS = "VIEW_LOCTITE_SUCCESS";
export const ON_CHANGE_LOCTITE_LIST = "ON_CHANGE_LOCTITE_LIST";
// new loctite
export const SUBMIT_LOCTITE_FORM = "SUBMIT_LOCTITE_FORM";
export const SUBMIT_LOCTITE_SUCCESS = "SUBMIT_LOCTITE_SUCCESS";
export const SUBMIT_LOCTITE_FAILURE = "SUBMIT_LOCTITE_FAILURE";
export const HANDLE_LOCTITE_FORM = "HANDLE_LOCTITE_FORM";
export const CLEAR_LOCTITE_FORM = "CLEAR_LOCTITE_FORM";
// edit
export const START_EDIT_LOCTITE = "START_EDIT_LOCTITE";
export const START_EDIT_LOCTITE_SUCCESS = "START_EDIT_LOCTITE_SUCCESS";
export const START_EDIT_LOCTITE_FAILURE = "START_EDIT_LOCTITE_FAILURE";
